### ISSUE TITLE
How to start Chat

### ISSUE THREAD

**Issue by pierreNomazy** [MegaMark16/django-live-support#2]
Hello,
What are the conditions to open the Chat : create an agent, then this agent open admin/live_support/chat/ ? but I have still the 'leave message' in the support ?
Pierre

**Comment by MegaMark16** [comment]
Ok, so here's how it works; out of the box if you don't setup Support Groups and assign users to those groups, you are using the global chat system, so all admins will set the admins_active cache variable and any users hitting either the root of the support app or a template with the chat_iframe templatetag dropped on it without any variables will be connected together.  

When an admin is on the Chat Admin screen and hitting the get_messages view automatically every few seconds to check for messages, it updates that admin_active cache variable so that the client chat view knows that admins are available and shows the Chat Now message.

So, if you setup one or more support groups and add users to those groups as either agents or supervisors, then you need to point users to either a chat page using the group's id (like /support/1/) or pass the group id as an argument to the chat_iframe templatetag (like {% chat_iframe 1 %}).  This way any users hitting those pages will only be connected to admins in the support groups that they should be linked with.  

I need to update the docs to correctly describe the above scenarios, but as I said, out of the box, with no groups assigned, you should be able to hit the support root url or drop the chat_iframe templatetag on a page and when you're logged in as an admin and on the chat admin screen it should show Chat Now for the client, not Leave a Message.
